mongo_db:
  image: mongo:3.2.1

web:
  build: .
  ports:
    - '80:80'
  links:
    - mongo_db
  environment:
    - MONGO_URL=mongodb://mongo_db/speki
    - ROOT_URL=http://0.0.0.0
    - SPEKI_FB_CLIENT_ID
    - SPEKI_FB_SECRET
